# Generated by Django 4.1 on 2022-08-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=2)),
                ('number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=2)),
                ('number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=2)),
                ('value', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Nazwa')),
                ('symbol', models.CharField(blank=True, max_length=8, verbose_name='Symbol')),
                ('atomic_number', models.SmallIntegerField(verbose_name='Liczba atomowa')),
                ('atomic_weight', models.FloatField(blank=True, default=1.0, verbose_name='Masa atomowa')),
                ('electro_negativity', models.FloatField(default=1.0, null=True, verbose_name='Elektroujemność')),
                ('atomic_radius', models.CharField(blank=True, max_length=64, verbose_name='Promień atomu')),
                ('year', models.IntegerField(blank=True, verbose_name='Rok odkrycia')),
                ('melting_temp', models.FloatField(blank=True, null=True, verbose_name='Temperatura topnienia')),
                ('boiling_temp', models.FloatField(blank=True, null=True, verbose_name='Temperatura wrzenia')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chemistry.block', verbose_name='Blok')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chemistry.character', verbose_name='Charakter chemiczny')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chemistry.group', verbose_name='Grupa')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chemistry.period', verbose_name='Okres')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chemistry.state', verbose_name='Stan skupienia')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chemistry.value', verbose_name='Wartościowość')),
            ],
        ),
    ]
