# Generated by Django 4.1 on 2022-08-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chemistry', '0002_remove_elements_value_elements_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='electro_negativity',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='Elektroujemność'),
        ),
    ]
