# Generated by Django 4.1 on 2022-08-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chemistry', '0003_alter_elements_electro_negativity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rok odkrycia'),
        ),
    ]
