# Generated by Django 4.1 on 2022-08-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chemistry', '0004_alter_elements_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='is_lanthanides',
            field=models.BooleanField(default=False),
        ),
    ]
