# Generated by Django 4.1 on 2022-08-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chemistry', '0005_elements_is_lanthanides'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='is_actinides',
            field=models.BooleanField(default=False),
        ),
    ]
