# Generated by Django 4.1 on 2022-08-07 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_chemistry', '0006_elements_is_actinides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='character',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_chemistry.character', verbose_name='Charakter chemiczny'),
        ),
        migrations.AlterField(
            model_name='elements',
            name='value',
            field=models.ManyToManyField(blank=True, to='app_chemistry.value', verbose_name='Wartościowość'),
        ),
    ]
