# Generated by Django 4.1 on 2022-08-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chemistry', '0007_alter_elements_character_alter_elements_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elements',
            name='value',
        ),
        migrations.AddField(
            model_name='elements',
            name='value',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
